/**
 * 预约状态枚举 - 前端版本
 * 与后端保持一致的枚举定义
 */

export const APPOINTMENT_STATUS = {
  PENDING: 'pending',
  CONFIRMED: 'confirmed',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled'
};

// 状态显示文本映射
export const APPOINTMENT_STATUS_TEXT = {
  [APPOINTMENT_STATUS.PENDING]: '待确认',
  [APPOINTMENT_STATUS.CONFIRMED]: '已确认',
  [APPOINTMENT_STATUS.COMPLETED]: '已完成',
  [APPOINTMENT_STATUS.CANCELLED]: '已取消'
};

// 状态流转规则
export const APPOINTMENT_STATUS_FLOW = {
  [APPOINTMENT_STATUS.PENDING]: [APPOINTMENT_STATUS.CONFIRMED, APPOINTMENT_STATUS.CANCELLED],
  [APPOINTMENT_STATUS.CONFIRMED]: [APPOINTMENT_STATUS.COMPLETED, APPOINTMENT_STATUS.CANCELLED],
  [APPOINTMENT_STATUS.COMPLETED]: [],
  [APPOINTMENT_STATUS.CANCELLED]: []
};

// 有效状态列表
export const VALID_STATUSES = Object.values(APPOINTMENT_STATUS);